name: Deploy Stored Procedures - Dev

on:
  push:
    branches:
      - test/ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install sqlcmd for SQL Server deployment (Ubuntu 24.04 compatible)
      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc

      # 3. Deploy stored procedures
      - name: Deploy stored procedures
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "---------------------------------------------"
          echo "Deploying stored procedures to SQL Server..."
          echo "Server   : $DB_SERVER"
          echo "Database : $DB_NAME"
          echo "User     : $DB_USER"
          echo "---------------------------------------------"

          for file in lambdas/HRHoudini_user_crud_dev/stored_procedures/user/*.sql; do
            if [ -f "$file" ]; then
              echo "Deploying $file..."
              /opt/mssql-tools18/bin/sqlcmd \
                -S $DB_SERVER \
                -U $DB_USER \
                -P $DB_PASSWORD \
                -d $DB_NAME \
                -C -b \
                -i "$file"
            else
              echo "No .sql files found in stored_procedures/user/"
            fi
          done

      # 4. Verify stored procedures after deployment
      - name: Verify stored procedures
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "Verifying stored procedures in $DB_NAME..."
          /opt/mssql-tools18/bin/sqlcmd \
            -S $DB_SERVER \
            -U $DB_USER \
            -P $DB_PASSWORD \
            -d $DB_NAME \
            -C \
            -Q "SELECT name, schema_name(schema_id) AS schema_name FROM sys.procedures;"
